apiVersion: maistra.io/v1
kind: ServiceMeshControlPlane
metadata:
  name: istio-system
spec:
  istio:
    global:
      imagePullPolicy: Always
      controlPlaneSecurityEnabled: false
      mtls:
        enabled: false
    kiali:
      enabled: true
    mixer:
      telemetry:
        autoscaleEnabled: false
        resources:
          requests:
            cpu: 100m
            memory: 1G
          limits:
            cpu: 500m
            memory: 4G
    pilot:
      autoscaleEnabled: false
      traceSampling: 100
    tracing:
      enabled: true
      jaeger:
        template: production-elasticsearch
        esIndexCleaner:
          enabled: true
          schedule: "*/5 * * * *"
          numberOfDays: 3
        elasticsearch:
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              memory: "1Gi"
  threeScale:
    enabled: false
  version: v1.1
