apiVersion: maistra.io/v2
kind: ServiceMeshControlPlane
metadata:
#  namespace: istio-system
  name: basic
spec:
  runtime:
    components:
      tracing.jaeger.elasticsearch:
        container:
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "1Gi"
  tracing:
    sampling: 10000
    type: Jaeger
  policy:
    type: Istiod
  addons:
    grafana:
      enabled: false
    jaeger:
      install:
        ingress:
          enabled: true
        storage:
          elasticsearch:
            nodeCount: 1
            redundancyPolicy: ZeroRedundancy
          type: Elasticsearch
      name: jaeger
    kiali:
      enabled: true
    prometheus:
      enabled: true
  version: v2.0
  telemetry:
    type: Istiod
